import React from "react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";

const HowItWorks: React.FC = () => {
  const { t } = useTranslation();

  return (
    <div className="max-w-4xl mx-auto md:px-4 px-2 md:py-8 py-2 relative">
      <Link
        to="/"
        className="absolute top-4 right-4 md:top-8 md:right-8 text-white hover:text-[#add6ea] transition-colors z-10"
        aria-label="Close"
      >
        <svg
          className="w-8 h-8"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M6 18L18 6M6 6l12 12"
          />
        </svg>
      </Link>
      <div className="bg-[#293a42] rounded-xl md:p-8 p-4 text-white">
        <h1 className="md:text-3xl text-2xl font-bold mb-6 text-center">
          {t("howItWorksTitle", "How It Works")}
        </h1>

        <div className="space-y-6">
          <div className="md:text-lg text-base leading-relaxed">
            <p className="mb-4">
              {t(
                "howItWorksIntro",
                'Welcome to "Who is Right?" — a funny little corner of the internet where people can settle friendly debates with the help of a totally unbiased, highly questionable… AI judge 🧑‍⚖️🤖'
              )}
            </p>
          </div>

          <div className="bg-[#1e2a30] rounded-lg p-6">
            <h2 className="md:text-xl text-lg font-semibold mb-4">
              {t("howItWorksSteps", "Here's how it works:")}
            </h2>
            <ol className="space-y-3 list-decimal list-inside">
              <li>
                <strong>{t("step1Title", "Write the Situation:")}</strong>{" "}
                {t(
                  "step1Description",
                  'At the top, type the argument or situation you\'re both "definitely right" about.'
                )}
              </li>
              <li>
                <strong>{t("step2Title", "Each Side Responds:")}</strong>{" "}
                {t(
                  "step2Description",
                  "Each of you gets your own input to tell your side of the story. Be honest… or at least entertaining!"
                )}
              </li>
              <li>
                <strong>{t("step3Title", "Let the AI Decide:")}</strong>{" "}
                {t(
                  "step3Description",
                  'Hit the magical "Who is right?" button and let the AI give its (often absurd) verdict.'
                )}
              </li>
            </ol>
          </div>

          <div className="bg-[#1e2a30] rounded-lg p-6">
            <h2 className="md:text-xl text-lg font-semibold mb-4 text-yellow-400">
              ⚠️ {t("importantDisclaimer", "Important Disclaimer")}
            </h2>
            <p className="mb-3">
              {t(
                "disclaimerText",
                "This app is meant for entertainment only. All answers are generated by AI and should never be taken seriously, legally, medically, romantically, or in any real-world way."
              )}
            </p>
            <ul className="space-y-2 list-disc list-inside text-sm">
              <li>
                {t(
                  "disclaimerPoint1",
                  "The AI does not know the truth, nor does it pretend to."
                )}
              </li>
              <li>
                {t(
                  "disclaimerPoint2",
                  "Never share sensitive, personal, or confidential information."
                )}
              </li>
            </ul>
          </div>

          <div className="bg-[#1e2a30] rounded-lg p-6">
            <h2 className="md:text-xl text-lg font-semibold mb-4 text-green-400">
              🔒 {t("yourData", "Your Data")}
            </h2>
            <p>
              {t(
                "dataPrivacy",
                "Your inputs are temporarily saved so our developers can monitor for abuse and improve safety. Data is not shared, not stored long-term, and never used for AI training. This is for security and moderation purposes only."
              )}
            </p>
          </div>

          <div className="text-center bg-[#1e2a30] rounded-lg p-6">
            <p className="md:text-lg text-base italic">
              {t(
                "finalMessage",
                "Have fun, don't fight too hard, and remember — the AI is always wrong… or right… or whatever it feels like today!"
              )}
            </p>
          </div>
        </div>

        <div className="mt-8 text-center">
          <Link
            to="/"
            className="inline-block bg-[#add6ea] text-[#131c20] px-6 py-3 rounded-full font-semibold hover:bg-[#8bc4d8] transition-colors"
          >
            {t("backToApp", "Back to App")}
          </Link>
        </div>
      </div>
    </div>
  );
};

export default HowItWorks;
